option('locking', type: 'boolean', value: true, description: 'Compile in support for locking the display')
option('kbd-layout-indicator', type: 'boolean', value: true, description: 'Enable keyboard layout indicator')
option('libnotify', type: 'boolean', value: true, description: 'Enable libnotify support')
option('systemd', type: 'feature', value: 'auto', description: 'Enable systemd support')
option('elogind', type: 'feature', value: 'auto', description: 'Use libelogind instead of libsystemd-login')
option('console-kit', type: 'boolean', value: true, description: 'Enable ConsoleKit support')
option('pam', type: 'boolean', value: true, description: 'Enable PAM support')
option('shadow', type: 'boolean', value: true, description: 'Enable shadow password support')
option('passwd-helper', type: 'string', value: '', description: 'Path to external password verification helper program (or "builtin")')
option('authentication-scheme', type: 'combo', choices: ['auto', 'pam', 'helper', 'pwent', 'bsdauth'], value: 'auto', description: 'Choose specific authentication scheme')
option('mit-ext', type: 'boolean', value: true, description: 'Include support for the MIT-SCREEN-SAVER extension')
option('xf86gamma-ext', type: 'boolean', value: true, description: 'Include support for XFree86 gamma fading')
option('libgl', type: 'feature', value: 'auto', description: 'Build with GL support')
option('xscreensaverdir', type: 'string', value: '', description: 'Directory containing xscreensaver hack configuration files')
option('xscreensaverhackdir', type: 'string', value: '', description: 'Directory containing xscreensaver hack executables')
option('docbook-docs', type: 'boolean', value: false, description: 'Build DocBook documentation')
option('doc-dir', type: 'string', value: '', description: 'Directory to install documentation')
option('pam-prefix', type: 'string', value: '', description: 'Directory where PAM files go')
option('autostart', type: 'boolean', value: true, description: 'Install the X11 screensaver in XDG autostart')
